### ISSUE TITLE
Don't add unknown visitor to server-side unions

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-java#164]
In general we don't support wire breaks - runtime validation will always throw with and old (pre-break) client hitting a new (post-break) server.

We're going to consider adding to a union okay (NOT a wire break), but removing from a union IS a wire break.

As a result, we can remove the "unknown" visitor from unions on the server side. If you break your union by removing a type, then our runtime validation will throw if old clients send that old type. Therefore -> no need for you to handle the unknown case on the server side.

**Comment by dannysheridan** [comment]
closing as this is 14 months old without activity
