### ISSUE TITLE
UUID alias is broken

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-java#166]
```
types:
  DiagnosisId: uuid
```

/fern/output/src/main/java/com/candid/api/client/diagnoses/types/DiagnosisId.java:45: error: incompatible types: String cannot be converted to UUID

https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/fern-prod/tasks/2ec162842518467eaeabd5262a591bc3/logs?region=us-east-1

**Comment by dsinghvi** [comment]
Closing b/c stale
