### ISSUE TITLE
Use Environment files instead of set output

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-java#195]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/fern-phyllo/phyllo-java/actions/runs/3381217180/jobs/5614882505

**Comment by dsinghvi** [comment]
closing b/c stale
