### ISSUE TITLE
Java SDK Compile Fails to Compile Due to Two Methods of the Same Name in CreateAnswerRequest.java

### ISSUE THREAD

**Issue by TeisJayaswal** [fern-api/fern-java#233]
# Summary

The Java SDK [fails to compile](https://github.com/fern-openai/open-ai-java/actions/runs/4266875888/jobs/7427890252#step:4:23). The issue is related to the same request: `CreateAnswerRequest`

```
error: name clash: examples(List<List<String>>) and examples(List<String>) have the same erasure
    public _FinalStage examples(List<List<String>> examples) {
```

```
error: name clash: examples(List<String>) in Builder and examples(List<List<String>>) in _FinalStage have the same erasure, yet neither overrides the other
    public _FinalStage examples(List<String> examples) {
```

This is happening because in the [CreateAnswersRequest file](https://github.com/fern-openai/open-ai-java/blob/1648a8f3fc9fc453d488fb28c55e695609de536c/src/main/java/com/open/ai/api/resources/answers/types/CreateAnswerRequest.java#L265
), there are two methods of the same name: 

```
_FinalStage examples(List<List<String>> examples);

_FinalStage examples(List<String> examples);
```
Java will transform these to 'examples(List)' and clash at runtime. 

## Expected Behavior 

If we update to differentiate the method names, this should compile. Differentiating the parameter types would be another solution.

**Comment by dannysheridan** [comment]
closing as this hasn't been user reported since
