### ISSUE TITLE
Attempting to pass request body to OkHTTP GET call

### ISSUE THREAD

**Issue by markphelps** [fern-api/fern-java#253]
see: https://github.com/flipt-io/flipt-java/issues/4

Flipt Java is using this generator. Upon one of our most recent releases: https://github.com/flipt-io/flipt-java/releases/tag/0.2.0, a user is reporting the following:

> The error is in `FlagsClientImpl.get`, as it's attempting to pass a request body to a GET call, which okhttp rejects: https://github.com/flipt-io/flipt-java/blob/eb35b840c9bdb48809ed1763edd372906e91cd41/src/main/java/com/flipt/api/resources/flags/FlagsClientImpl.java#L102

> Stack trace:
```
java.lang.IllegalArgumentException: method GET must not have a request body.
	at okhttp3.Request$Builder.method(Request.kt:258) ~[okhttp-4.10.0.jar:na]
	at com.flipt.api.resources.flags.FlagsClientImpl.get(FlagsClientImpl.java:102) ~[flipt-java-0.2.0.jar:na]
	...
```

**Comment by dsinghvi** [comment]
Thanks @markphelps, working on this now! Will link a PR when it's up.

**Comment by dsinghvi** [comment]
Here's the PR: https://github.com/fern-api/fern-java/pull/254

**Comment by dsinghvi** [comment]
https://github.com/fern-api/fern-java/releases/tag/0.2.1-rc0 just released an RC version @markphelps
