### ISSUE TITLE
"No value present" error when generating the initial example

### ISSUE THREAD

**Issue by aommm** [fern-api/fern-java#275]
Hello!

I'm trying to run `fern-java` on the initial IMDB example but I get an error:

```
> fern init
> fern add fern-java
> fern generate
[api]: fernapi/fern-java No value present
[api]: fernapi/fern-openapi Downloaded to /Users/aom/core/generated/openapi
[api]: fernapi/fern-typescript-node-sdk Downloaded to /Users/aom/core/generated/typescript
┌─
│ ✓  fernapi/fern-typescript-node-sdk
│ ✓  fernapi/fern-openapi
│ x  fernapi/fern-java
└─
```

My fern version is `0.9.9` and my fern-java version is `0.0.122`.

**Comment by zachkirsch** [comment]
Hey @aommm! Rough start, sorry about that :)

`fern-java` is deprecated. To generate a Java SDK, you can use this configuration in your `generators.yml`:

```yaml
      - name: fernapi/fern-java-sdk
        version: 0.3.6
```

You can see the full list of our generators here: https://buildwithfern.com/docs/compiler/generators

**Comment by aommm** [comment]
Got it, thanks for the quick reply!

I was looking for a way to generate a server interface; I guess you don't have an official generator for that anymore? Is it on your roadmap or are you focusing more on SDK generation?

(ideally I'm looking for a Scala server & client generator but that's probably too much to ask for 😉)

**Comment by dsinghvi** [comment]
@aommm We support generating Java Spring and Dropwizard interfaces, checkout this repo(https://github.com/fern-api/spring-starter) how to generate java spring.

The name of the generator for java spring is `fernapi/fern-java-spring`

**Comment by dsinghvi** [comment]
@aommm closing out this issue, feel free to open if its still an issue!
