### ISSUE TITLE
Undefined _request variable in generated client methods

### ISSUE THREAD

**Issue by Norbo11** [fern-api/fern-java#279]
Steps to repro:

```
fern init --openapi https://ob.gocardless.com/api/v2/swagger.json
fern add fern-java-sdk
fern generate
```

The client code doesn't compile at this point because it references an undefined `_request` variable in some of the client method bodies. 

I think it's due to [HttpUrlBuilder.generateUnInlineableCodeBlock](https://github.com/fern-api/fern-java/blob/main/client-generator/src/main/java/com/fern/java/client/generators/endpoint/HttpUrlBuilder.java#L86)  somehow passing a `requestName` of `_request` rather than `request` when generating the `if ($L.$N().isPresent())` statements.

**Comment by dsinghvi** [comment]
@Norbo11 This should be fixed in the latest release, closing now! Let me know if you have any issues with it!
