### ISSUE TITLE
Generated client code throws a RuntimeException with no context when a non 2XX response is encountered

### ISSUE THREAD

**Issue by Norbo11** [fern-api/fern-java#280]
Steps to repro:

```
fern init --openapi https://ob.gocardless.com/api/v2/swagger.json
fern add fern-java-sdk
fern generate
```

Some of the generated methods look as follows:

```java
  @Override
  public Requisition requisitionById(String id) {
    Request _request = new Request.Builder()
      .url(
        HttpUrl
          .parse(this.clientOptions.environment().getUrl())
          .newBuilder()
          .addPathSegments("api/v2/requisitions")
          .addPathSegment(id)
          .build()
      )
      .method("GET", null)
      .headers(Headers.of(clientOptions.headers()))
      .addHeader("Content-Type", "application/json")
      .build();
    try {
      Response _response = clientOptions.httpClient().newCall(_request).execute();
      if (_response.isSuccessful()) {
        return ObjectMappers.JSON_MAPPER.readValue(_response.body().string(), Requisition.class);
      }
      throw new RuntimeException();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
```

Fern checks if the response is successful and correctly deserializes the response. But if `_response.isSuccessful()` is `false`, then it throws `new RuntimeException();` which contains no context around what actually failed.

I would expect `fern` to wrap this with some kind of `ApiException extends RuntimeException` type, containing the raw body that was returned in the response, the status code, etc. It should also set `message` to something appropriate (e.g. the raw body truncated to some character limit?)

**Comment by dsinghvi** [comment]
@Norbo11 on the latest version this should be fixed, we not return an `ApiError`. Soon this will be renamed to `{ApiName}Exception`.
