### ISSUE TITLE
Clients generated from package configuration missing path

### ISSUE THREAD

**Issue by GeorgeMac** [fern-api/fern-java#306]
We (@flipt-io) had a user report an issue with our Java client today.
They were getting a 404, which was raised as a runtime exception.
However, when they looked closer they noticed that the client wasn't requesting the correct path.

We recently added these new endpoints and we did so via the `__package__.yml` approach, which was a first for us.
https://github.com/flipt-io/flipt-api/blob/39c1923b70eb3255044c0f5f5d285e5b47289ebc/fern/api/definition/evaluation/__package__.yml#L6-L23

Notice the three endpoints for `variant`, `boolean` and `batch`.

However, the generated Java client doesn't contain these path suffixes.
Instead, each of these generated methods all POST to the same endpoint, which is just the prefix `/evaluate/v1`:

https://github.com/flipt-io/flipt-java/blob/0.2.8/src/main/java/com/flipt/api/resources/evaluation/EvaluationClientImpl.java#L59C1-L62

The node client appears to be generating properly, so I assumed this is a bug in this package.

**Comment by dsinghvi** [comment]
Closing as it is fixed on the latest generator version
