### ISSUE TITLE
Support Java8

### ISSUE THREAD

**Issue by markphelps** [fern-api/fern-java#352]
Re: https://github.com/flipt-io/flipt-java/pull/23#issuecomment-1741754127

We would like to integrate our Fern-generated Java SDK into another SDK that requires Java8 compatibility.

Currently, the Fern-generated SDK includes some code that is not Java8 compatible, mainly the use of [`Map.of`](https://www.concretepage.com/java/java-9/java-map-of-and-map-ofentries) (added in Java 8 I believe) for setting request headers. Example: https://github.com/flipt-io/flipt-java/pull/23/files#diff-c8eabd1acf42a6a24194ed2167e131ad45701f2fdab9b6d56885362c6b28779bL25-L31

Also, it would be great if we could configure setting the `toolchain` directive in the generated `build.gradle file: https://github.com/flipt-io/flipt-java/pull/23/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R32-R34

Please let me know if there are any questions! Thanks!

**Comment by dannysheridan** [comment]
closing as this is deprioritized for now 😢
