### ISSUE TITLE
[Feature] Build Docker image to speed-up seed tests

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern-java#377]
**Is your feature request related to a problem? Please describe.**

Now that we're testing that the generated seed output compiles (re: https://github.com/fern-api/fern-java/pull/375), tests take way too long to finish (i.e. ~20min).

**Describe the solution you'd like**

We should build our own Docker image that comes with all the required dependencies pre-installed so that we can speed this up.

**Describe alternatives you've considered**

No alternatives considered - we _definitely_ want to verify the generated code compiles and this still appears to be the best way to do so.

**Comment by dannysheridan** [comment]
closing as we haven't gotten a customer ask for this
